# Generated by Django 5.2 on 2025-04-23 16:03

import django.db.models.deletion
import noticias.models
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('descripcion', tinymce.models.HTMLField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('General', 'General'), ('Politica', 'Política'), ('Economia', 'Economía'), ('Comunicado Oficial', 'Comunicado Oficial'), ('Deportes', 'Deportes'), ('Cultura', 'Cultura'), ('Tecnologia', 'Tecnología')], default='general', max_length=20, verbose_name='Tipo de Noticia')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
            },
        ),
        migrations.CreateModel(
            name='ArchivosNoticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=noticias.models.ArchivosNoticias.archivo_ruta)),
                ('tipo_archivo', models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video'), ('documento', 'Documento'), ('otro', 'Otro')], max_length=20)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='noticias.noticias')),
            ],
            options={
                'verbose_name': 'archivo',
                'verbose_name_plural': 'archivos de la noticia',
            },
        ),
    ]
