# Generated by Django 5.2 on 2025-04-24 20:40

import noticias.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivosnoticias',
            name='archivo_url',
            field=models.URLField(blank=True, help_text='Pega aquí la URL si el archivo es muy grande o ya está en S3.', max_length=500, null=True, verbose_name='Enlace directo al archivo'),
        ),
        migrations.AlterField(
            model_name='archivosnoticias',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to=noticias.models.ArchivosNoticias.archivo_ruta),
        ),
    ]
