# Generated by Django 5.2 on 2025-04-30 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='jornada',
            field=models.CharField(choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde'), ('Nocturna', 'Nocturna')], default='Mañana', max_length=20, verbose_name='Jornada'),
        ),
    ]
