# Generated by Django 5.1.1 on 2024-10-08 17:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_noticias_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunidad',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de publicación'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de publicación'),
        ),
        migrations.AlterField(
            model_name='implementaciones',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de publicación'),
        ),
        migrations.AlterField(
            model_name='institucional',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de publicación'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de publicación'),
        ),
    ]
