# Generated by Django 5.1.1 on 2024-10-15 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_comunidad_fecha_alter_eventos_fecha_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comunidad',
            new_name='ComunidadEducativa',
        ),
        migrations.AlterModelOptions(
            name='comunidadeducativa',
            options={'verbose_name': 'Comunidad Educativa', 'verbose_name_plural': 'Comunidad Educativa'},
        ),
        migrations.AlterModelOptions(
            name='eventos',
            options={'verbose_name': 'Eventos', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='implementaciones',
            options={'verbose_name': 'Implementaciónes', 'verbose_name_plural': 'Implementaciones'},
        ),
        migrations.AlterModelOptions(
            name='institucional',
            options={'verbose_name': 'Institucional', 'verbose_name_plural': 'Institucional'},
        ),
        migrations.AlterModelOptions(
            name='noticias',
            options={'ordering': ['-fecha'], 'verbose_name': 'Noticias', 'verbose_name_plural': 'Noticias'},
        ),
    ]
