# Generated by Django 5.1.1 on 2024-10-21 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_comunidad_comunidadeducativa_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ComunidadEducativa',
            new_name='Comunidad',
        ),
        migrations.AlterModelOptions(
            name='comunidad',
            options={'verbose_name': 'Comunidad', 'verbose_name_plural': 'Comunidad'},
        ),
    ]
