# Generated by Django 5.1.6 on 2025-04-14 19:50

import django.db.models.deletion
import general.models
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('descripcion', tinymce.models.HTMLField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='Implementaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('descripcion', tinymce.models.HTMLField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Implementación',
                'verbose_name_plural': 'Implementaciones',
            },
        ),
        migrations.CreateModel(
            name='Institucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('descripcion', tinymce.models.HTMLField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Institucional',
                'verbose_name_plural': 'Institucional',
            },
        ),
        migrations.CreateModel(
            name='ArchivosEventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=general.models.ArchivosEventos.archivo_ruta)),
                ('tipo_archivo', models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video'), ('documento', 'Documento'), ('otro', 'Otro')], max_length=20)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='general.eventos')),
            ],
            options={
                'verbose_name': 'archivo',
                'verbose_name_plural': 'archivos de eventos',
            },
        ),
        migrations.CreateModel(
            name='ArchivosImplementaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=general.models.ArchivosImplementaciones.archivo_ruta)),
                ('tipo_archivo', models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video'), ('documento', 'Documento'), ('otro', 'Otro')], max_length=20)),
                ('implementacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='general.implementaciones')),
            ],
            options={
                'verbose_name': 'archivo',
                'verbose_name_plural': 'archivos de implementaciones',
            },
        ),
        migrations.CreateModel(
            name='ArchivosInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=general.models.ArchivosInstitucional.archivo_ruta)),
                ('tipo_archivo', models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video'), ('documento', 'Documento'), ('otro', 'Otro')], max_length=20)),
                ('institucional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='general.institucional')),
            ],
            options={
                'verbose_name': 'archivo',
                'verbose_name_plural': 'archivos institucionales',
            },
        ),
    ]
