# Generated by Django 5.1.6 on 2025-02-23 19:27

import django.db.models.deletion
import general.models
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('descripcion', tinymce.models.HTMLField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='Implementaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('descripcion', tinymce.models.HTMLField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Implementación',
                'verbose_name_plural': 'Implementaciones',
            },
        ),
        migrations.CreateModel(
            name='Institucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('descripcion', tinymce.models.HTMLField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Institucional',
                'verbose_name_plural': 'Institucional',
            },
        ),
        migrations.CreateModel(
            name='ImagenesEventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=general.models.ImagenesEventos.imagen_ruta)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='general.eventos')),
            ],
            options={
                'verbose_name': 'imagen',
                'verbose_name_plural': 'imagenes de eventos',
            },
        ),
        migrations.CreateModel(
            name='ImagenesImplementaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=general.models.ImagenesImplementaciones.imagen_ruta)),
                ('implementacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='general.implementaciones')),
            ],
            options={
                'verbose_name': 'imagen',
                'verbose_name_plural': 'imagenes de implementaciones',
            },
        ),
        migrations.CreateModel(
            name='ImagenesInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=general.models.ImagenesInstitucional.imagen_ruta)),
                ('institucional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='general.institucional')),
            ],
            options={
                'verbose_name': 'imagen',
                'verbose_name_plural': 'imagenes de institucional',
            },
        ),
    ]
