# Generated by Django 5.2 on 2025-04-30 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_eventos_jornada_implementaciones_jornada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='jornada',
            field=models.CharField(choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde'), ('Nocturna', 'Nocturna'), ('General', 'General')], default='General', max_length=20, verbose_name='Jornada'),
        ),
        migrations.AlterField(
            model_name='implementaciones',
            name='jornada',
            field=models.CharField(choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde'), ('Nocturna', 'Nocturna'), ('General', 'General')], default='General', max_length=20, verbose_name='Jornada'),
        ),
        migrations.AlterField(
            model_name='institucional',
            name='jornada',
            field=models.CharField(choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde'), ('Nocturna', 'Nocturna'), ('General', 'General')], default='General', max_length=20, verbose_name='Jornada'),
        ),
    ]
